query getComments {
	comments {
		content {
			id
			comment
			createdOn
			author
			talk {
				id
				title
				summary
			}
		}
		pageInfo {
			totalElements
			totalPages
			numberOfElements
			pageNumber
			pageSize
		}
	}
}